### ISSUE TITLE
RSS feeds

### ISSUE THREAD

**Issue by Splike** [ChangeWindows/Content#9]
I'd very much like to see the adition of RSS feeds to the website. I wrote to you guys on facebook, but i'll write my idea here as well, in case you don't see my message.

Four different feeds should be made:
1) Desktop only updates (http://changewindows.org/desktop.php)
2) Mobile only updates (http://changewindows.org/mobile.php)
3) Phone only updates (http://changewindows.org/phone.php)
4) All three categories in one feed

Let me know what you think of the idea.

**Comment by Studio384** [comment]
We're investigating this feature now.

**Comment by Splike** [comment]
Glad to hear this. I'll be looking forward to it.

**Comment by Studio384** [comment]
Closing this issue as it will be tracked in our new website repository for ChangeWindows 5.0.

**Comment by Studio384** [comment]
It took us **WAY** to long to get around to doing this but I'm glad to say that this finally landed in ChangeWindows viv and is now up on our preview site (https://viv.changewindows.org) and will soon be available on our main website.
